[tool.towncrier]
    version = "2.0.0"
    directory = "changelog.d"
    filename = "TCHAP_CHANGES.md"
    name = "Changes in Tchap"
    template = "tools/towncrier/template.md"
    issue_format = "[#{issue}](https://github.com/tchapgouv/tchap-android-v2/issues/{issue})"

    [[tool.towncrier.type]]
        directory = "feature"
        name = "Features ✨"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "improvements"
        name = "Improvements 🙌"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "bugfix"
        name = "Bugfixes 🐛"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "doc"
        name = "Improved Documentation 📚"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "SDK API changes ⚠️"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "misc"
        name = "Other changes"
        showcontent = true
